Unison:U0.2:S4.3;

Pattern dmled_read_DPM {

Mode Digital;
Type Generic;



Default SignalHeader DefaultSignalHeader;

Default WaveformTable WFT11;

" Processed by Jazz::Tvt::tvtFusion version 1.199.0, updated Nov 22, 2011 "
" TDL:  TDLS/dmled_read_v22.tdl.gz "
" Generated:  Wed Dec 28 17:58:15 US/Central 2011 "
" Jazz dir: /data/jazztest4/vikas/Phoenix_Unison/Blizzard_FX1 "

" ASIC_VERSION = 7.0 "
" "
" ASIC_TITLE = 'LIBRARY_TYPE = GS60, "
"                   CUSTOMER = TexasInstruments, "
"             TI_PART_NUMBER = F771727B, "
"           PATTERN_SET_NAME = dmled_read, "
"           PATTERN_SET_TYPE = FUNC,NOSTROBE, "
"    PATTERN_SET_DESCRIPTION = , "
"                   REVISION = 2.2, "
"                       DATE = 11/03/10'; "

/*   Started Reset Mode Entry Sequence      */
/* Assert reset */
/*
"AAAAPPrPPPAAAAPPPPPPPPPCCCCooPPPPPPPPPPRPPPPPFFFPPPPPPPPPTTTTPPPPPwhXXPPPPPPLLLLLLROOUUPPPiLLLLLLPPPPTTTTPPPPPRPPCCPPAAAAAAAAAAA"
"IIIIQQbBBQIIIINHHHHHHHH0011__AAAAAAGGPPAQQQQQLLLGGGGGGFFFRRRRFNNNNaiOOPPPPMMPPPPPPSSSSSBBBaPPPPPPKKKKDDMCNJJJJAPO22JJIIIIIIIIIII"
"NNNN01i672NNNN276543210____cc2345677625W34567AAA543210765DDDD37654kbSS341076CCCCCCTCCBB012_CCCCCC7654OISK30123W6R__67NNNNNNNNNNN"
"1111__a___1111_________nppnpp__________P_____SSS_________3210_____e_CC______000000_0100___f000000_____________P__pn__22221100000"
"543256s1116789222333344____uu4455555555O66666HHH777788888____99999_n01111111CSACSPn__DD111tRFAAAA1111111111111O1O__1132101098765"
"____  _056____7890567014444__8901456789R12345345678901456888914567n___000011LE2LCD_11MP233eERDDDD4444455555566R6R1177___________"
"1234  9   2222         2345df          _     ___         7890     _911678901KR0KI_122__901sSA01231234901238901_3I776711111111111"
"          3456             oa          n     777                  9900      _I_R_n24511   tEM____             N D45  77888888999"
"                           ni          _     012                  8 02      1R1Un_2  22   aTE1111             _ E    89012389012"
"                           el          6                                    1Q1N_1   78   d__3334             T _               "
"                           __          0                                    6_8_12        cnn7890             E 1               "
"                           44                                                1 n21        ___                 S 6               "
"                           67                                                1 _0         111                 T 4               "
"                                                                             7 1          333                 _                 "
"                                                                               1          256                 1                 "
"                                                                               9                              6                 "
"                                                                                                              2                 "
*/
$dmled_read_DPM_st
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;"1 (TDL line 219)"

"(*$ Reset JTAG TAP *)"
"(*$ Run Test Idle *)
 (*$ Test logic reset *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLCMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 17>"2-18 (TDL lines 223-231)"

"(*$0011:00000101011101000101010011100101 *)"
"(*$ Select DR Scan *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"19-20 (TDL lines 238-239) (*$ Select IR Scan *)"
"(*$ Capture IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"21-22 (TDL lines 240-241) (*$ Shift IR *)"
"(*$ BIT: 0*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"23-24 (TDL lines 242-243) (*$ BIT: 1*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"25 (TDL line 244) (*$ BIT: 2*)"
"(*$ BIT: 3 Shift and Exit IR*)"
"(*$ Update IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"26-28 (TDL lines 245-247) (*$ Select DR Scan *)"
"(*$ Capture DR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"29-30 (TDL lines 248-249) (*$ Shift DR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"31 (TDL line 250) (*$ BIT: 0*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"32 (TDL line 251) (*$ BIT: 1*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"33 (TDL line 252) (*$ BIT: 2*)"
"(*$ BIT: 3*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"34-35 (TDL lines 253-254) (*$ BIT: 4*)"
"(*$ BIT: 5*)"
"(*$ BIT: 6*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"36-38 (TDL lines 255-257) (*$ BIT: 7*)"
"(*$ BIT: 8*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"39-40 (TDL lines 258-259) (*$ BIT: 9*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"41 (TDL line 260) (*$ BIT: 10*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"42 (TDL line 261) (*$ BIT: 11*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"43 (TDL line 262) (*$ BIT: 12*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"44 (TDL line 263) (*$ BIT: 13*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"45 (TDL line 264) (*$ BIT: 14*)"
"(*$ BIT: 15*)"
"(*$ BIT: 16*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"46-48 (TDL lines 265-267) (*$ BIT: 17*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"49 (TDL line 268) (*$ BIT: 18*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"50 (TDL line 269) (*$ BIT: 19*)"
"(*$ BIT: 20*)"
"(*$ BIT: 21*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"51-53 (TDL lines 270-272) (*$ BIT: 22*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"54 (TDL line 273) (*$ BIT: 23*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"55 (TDL line 274) (*$ BIT: 24*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"56 (TDL line 275) (*$ BIT: 25*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"57 (TDL line 276) (*$ BIT: 26*)"
"(*$ BIT: 27*)"
"(*$ BIT: 28*)
 (*$ BIT: 29*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 4>"58-61 (TDL lines 277-280) (*$ BIT: 30*)"
"(*$Shift and Exit DR  BIT: 31 *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"62-63 (TDL lines 281-282) (*$ Update DR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"64 (TDL line 283) (*$ Run Test Idle *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;"65 (TDL line 284) (*$ Run Test Idle *)"

"(*$0101:00010010 *)"
"(*$ Select DR Scan *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"66-67 (TDL lines 287-288) (*$ Select IR Scan *)"
"(*$ Capture IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"68-69 (TDL lines 289-290) (*$ Shift IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"70 (TDL line 291) (*$ BIT: 0*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"71 (TDL line 292) (*$ BIT: 1*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"72 (TDL line 293) (*$ BIT: 2*)"
"(*$ BIT: 3 Shift and Exit IR*)"
"(*$ Update IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"73-75 (TDL lines 294-296) (*$ Select DR Scan *)"
"(*$ Capture DR *)"
"(*$ Shift DR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"76-78 (TDL lines 297-299) (*$ BIT: 0*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"79 (TDL line 300) (*$ BIT: 1*)"
"(*$ BIT: 2*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"80-81 (TDL lines 301-302) (*$ BIT: 3*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"82 (TDL line 303) (*$ BIT: 4*)"
"(*$ BIT: 5*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"83-84 (TDL lines 304-305) (*$ BIT: 6*)"
"(*$Shift and Exit DR  BIT: 7 *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"85-86 (TDL lines 306-307) (*$ Update DR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"87 (TDL line 308) (*$ Run Test Idle *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;"88 (TDL line 309) (*$ Run Test Idle *)"

"(*$0110:000010000000000000000100110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 *)"
"(*$ Select DR Scan *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"89-90 (TDL lines 312-313) (*$ Select IR Scan *)"
"(*$ Capture IR *)"
"(*$ Shift IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"91-93 (TDL lines 314-316) (*$ BIT: 0*)"
"(*$ BIT: 1*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"94-95 (TDL lines 317-318) (*$ BIT: 2*)"
"(*$ BIT: 3 Shift and Exit IR*)"
"(*$ Update IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"96-98 (TDL lines 319-321) (*$ Select DR Scan *)"
"(*$ Capture DR *)"
"(*$ Shift DR *)
 (*$ BIT: 0*)
 (*$ BIT: 1*)
 (*$ BIT: 2*)
 (*$ BIT: 3*)
 (*$ BIT: 4*)
 (*$ BIT: 5*)
 (*$ BIT: 6*)
 (*$ BIT: 7*)
 (*$ BIT: 8*)
 (*$ BIT: 9*)
 (*$ BIT: 10*)
 (*$ BIT: 11*)
 (*$ BIT: 12*)
 (*$ BIT: 13*)
 (*$ BIT: 14*)
 (*$ BIT: 15*)
 (*$ BIT: 16*)
 (*$ BIT: 17*)
 (*$ BIT: 18*)
 (*$ BIT: 19*)
 (*$ BIT: 20*)
 (*$ BIT: 21*)
 (*$ BIT: 22*)
 (*$ BIT: 23*)
 (*$ BIT: 24*)
 (*$ BIT: 25*)
 (*$ BIT: 26*)
 (*$ BIT: 27*)
 (*$ BIT: 28*)
 (*$ BIT: 29*)
 (*$ BIT: 30*)
 (*$ BIT: 31*)
 (*$ BIT: 32*)
 (*$ BIT: 33*)
 (*$ BIT: 34*)
 (*$ BIT: 35*)
 (*$ BIT: 36*)
 (*$ BIT: 37*)
 (*$ BIT: 38*)
 (*$ BIT: 39*)
 (*$ BIT: 40*)
 (*$ BIT: 41*)
 (*$ BIT: 42*)
 (*$ BIT: 43*)
 (*$ BIT: 44*)
 (*$ BIT: 45*)
 (*$ BIT: 46*)
 (*$ BIT: 47*)
 (*$ BIT: 48*)
 (*$ BIT: 49*)
 (*$ BIT: 50*)
 (*$ BIT: 51*)
 (*$ BIT: 52*)
 (*$ BIT: 53*)
 (*$ BIT: 54*)
 (*$ BIT: 55*)
 (*$ BIT: 56*)
 (*$ BIT: 57*)
 (*$ BIT: 58*)
 (*$ BIT: 59*)
 (*$ BIT: 60*)
 (*$ BIT: 61*)
 (*$ BIT: 62*)
 (*$ BIT: 63*)
 (*$ BIT: 64*)
 (*$ BIT: 65*)
 (*$ BIT: 66*)
 (*$ BIT: 67*)
 (*$ BIT: 68*)
 (*$ BIT: 69*)
 (*$ BIT: 70*)
 (*$ BIT: 71*)
 (*$ BIT: 72*)
 (*$ BIT: 73*)
 (*$ BIT: 74*)
 (*$ BIT: 75*)
 (*$ BIT: 76*)
 (*$ BIT: 77*)
 (*$ BIT: 78*)
 (*$ BIT: 79*)
 (*$ BIT: 80*)
 (*$ BIT: 81*)
 (*$ BIT: 82*)
 (*$ BIT: 83*)
 (*$ BIT: 84*)
 (*$ BIT: 85*)
 (*$ BIT: 86*)
 (*$ BIT: 87*)
 (*$ BIT: 88*)
 (*$ BIT: 89*)
 (*$ BIT: 90*)
 (*$ BIT: 91*)
 (*$ BIT: 92*)
 (*$ BIT: 93*)
 (*$ BIT: 94*)
 (*$ BIT: 95*)
 (*$ BIT: 96*)
 (*$ BIT: 97*)
 (*$ BIT: 98*)
 (*$ BIT: 99*)
 (*$ BIT: 100*)
 (*$ BIT: 101*)
 (*$ BIT: 102*)
 (*$ BIT: 103*)
 (*$ BIT: 104*)
 (*$ BIT: 105*)
 (*$ BIT: 106*)
 (*$ BIT: 107*)
 (*$ BIT: 108*)
 (*$ BIT: 109*)
 (*$ BIT: 110*)
 (*$ BIT: 111*)
 (*$ BIT: 112*)
 (*$ BIT: 113*)
 (*$ BIT: 114*)
 (*$ BIT: 115*)
 (*$ BIT: 116*)
 (*$ BIT: 117*)
 (*$ BIT: 118*)
 (*$ BIT: 119*)
 (*$ BIT: 120*)
 (*$ BIT: 121*)
 (*$ BIT: 122*)
 (*$ BIT: 123*)
 (*$ BIT: 124*)
 (*$ BIT: 125*)
 (*$ BIT: 126*)
 (*$ BIT: 127*)
 (*$ BIT: 128*)
 (*$ BIT: 129*)
 (*$ BIT: 130*)
 (*$ BIT: 131*)
 (*$ BIT: 132*)
 (*$ BIT: 133*)
 (*$ BIT: 134*)
 (*$ BIT: 135*)
 (*$ BIT: 136*)
 (*$ BIT: 137*)
 (*$ BIT: 138*)
 (*$ BIT: 139*)
 (*$ BIT: 140*)
 (*$ BIT: 141*)
 (*$ BIT: 142*)
 (*$ BIT: 143*)
 (*$ BIT: 144*)
 (*$ BIT: 145*)
 (*$ BIT: 146*)
 (*$ BIT: 147*)
 (*$ BIT: 148*)
 (*$ BIT: 149*)
 (*$ BIT: 150*)
 (*$ BIT: 151*)
 (*$ BIT: 152*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 156>"99-254 (TDL lines 322-477) (*$ BIT: 153*)"
"(*$ BIT: 154*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"255-256 (TDL lines 478-479) (*$ BIT: 155*)"
"(*$ BIT: 156*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"257-258 (TDL lines 480-481) (*$ BIT: 157*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"259 (TDL line 482) (*$ BIT: 158*)"
"(*$ BIT: 159*)"
"(*$ BIT: 160*)
 (*$ BIT: 161*)
 (*$ BIT: 162*)
 (*$ BIT: 163*)
 (*$ BIT: 164*)
 (*$ BIT: 165*)
 (*$ BIT: 166*)
 (*$ BIT: 167*)
 (*$ BIT: 168*)
 (*$ BIT: 169*)
 (*$ BIT: 170*)
 (*$ BIT: 171*)
 (*$ BIT: 172*)
 (*$ BIT: 173*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 16>"260-275 (TDL lines 483-498) (*$ BIT: 174*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"276 (TDL line 499) (*$ BIT: 175*)"
"(*$ BIT: 176*)"
"(*$ BIT: 177*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"277-279 (TDL lines 500-502) (*$ BIT: 178*)"
"(*$Shift and Exit DR  BIT: 179 *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"280-281 (TDL lines 503-504) (*$ Update DR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"282 (TDL line 505) (*$ Run Test Idle *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;"283 (TDL line 506) (*$ Run Test Idle *)"

"(*$0101:00001011 *)"
"(*$ Select DR Scan *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"284-285 (TDL lines 509-510) (*$ Select IR Scan *)"
"(*$ Capture IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"286-287 (TDL lines 511-512) (*$ Shift IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"288 (TDL line 513) (*$ BIT: 0*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"289 (TDL line 514) (*$ BIT: 1*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"290 (TDL line 515) (*$ BIT: 2*)"
"(*$ BIT: 3 Shift and Exit IR*)"
"(*$ Update IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"291-293 (TDL lines 516-518) (*$ Select DR Scan *)"
"(*$ Capture DR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"294-295 (TDL lines 519-520) (*$ Shift DR *)"
"(*$ BIT: 0*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"296-297 (TDL lines 521-522) (*$ BIT: 1*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"298 (TDL line 523) (*$ BIT: 2*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"299 (TDL line 524) (*$ BIT: 3*)"
"(*$ BIT: 4*)"
"(*$ BIT: 5*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"300-302 (TDL lines 525-527) (*$ BIT: 6*)"
"(*$Shift and Exit DR  BIT: 7 *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"303-304 (TDL lines 528-529) (*$ Update DR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"305 (TDL line 530) (*$ Run Test Idle *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;"306 (TDL line 531) (*$ Run Test Idle *)"

"(*$0110:000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 *)"
"(*$ Select DR Scan *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"307-308 (TDL lines 534-535) (*$ Select IR Scan *)"
"(*$ Capture IR *)"
"(*$ Shift IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"309-311 (TDL lines 536-538) (*$ BIT: 0*)"
"(*$ BIT: 1*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"312-313 (TDL lines 539-540) (*$ BIT: 2*)"
"(*$ BIT: 3 Shift and Exit IR*)"
"(*$ Update IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"314-316 (TDL lines 541-543) (*$ Select DR Scan *)"
"(*$ Capture DR *)"
"(*$ Shift DR *)
 (*$ BIT: 0*)
 (*$ BIT: 1*)
 (*$ BIT: 2*)
 (*$ BIT: 3*)
 (*$ BIT: 4*)
 (*$ BIT: 5*)
 (*$ BIT: 6*)
 (*$ BIT: 7*)
 (*$ BIT: 8*)
 (*$ BIT: 9*)
 (*$ BIT: 10*)
 (*$ BIT: 11*)
 (*$ BIT: 12*)
 (*$ BIT: 13*)
 (*$ BIT: 14*)
 (*$ BIT: 15*)
 (*$ BIT: 16*)
 (*$ BIT: 17*)
 (*$ BIT: 18*)
 (*$ BIT: 19*)
 (*$ BIT: 20*)
 (*$ BIT: 21*)
 (*$ BIT: 22*)
 (*$ BIT: 23*)
 (*$ BIT: 24*)
 (*$ BIT: 25*)
 (*$ BIT: 26*)
 (*$ BIT: 27*)
 (*$ BIT: 28*)
 (*$ BIT: 29*)
 (*$ BIT: 30*)
 (*$ BIT: 31*)
 (*$ BIT: 32*)
 (*$ BIT: 33*)
 (*$ BIT: 34*)
 (*$ BIT: 35*)
 (*$ BIT: 36*)
 (*$ BIT: 37*)
 (*$ BIT: 38*)
 (*$ BIT: 39*)
 (*$ BIT: 40*)
 (*$ BIT: 41*)
 (*$ BIT: 42*)
 (*$ BIT: 43*)
 (*$ BIT: 44*)
 (*$ BIT: 45*)
 (*$ BIT: 46*)
 (*$ BIT: 47*)
 (*$ BIT: 48*)
 (*$ BIT: 49*)
 (*$ BIT: 50*)
 (*$ BIT: 51*)
 (*$ BIT: 52*)
 (*$ BIT: 53*)
 (*$ BIT: 54*)
 (*$ BIT: 55*)
 (*$ BIT: 56*)
 (*$ BIT: 57*)
 (*$ BIT: 58*)
 (*$ BIT: 59*)
 (*$ BIT: 60*)
 (*$ BIT: 61*)
 (*$ BIT: 62*)
 (*$ BIT: 63*)
 (*$ BIT: 64*)
 (*$ BIT: 65*)
 (*$ BIT: 66*)
 (*$ BIT: 67*)
 (*$ BIT: 68*)
 (*$ BIT: 69*)
 (*$ BIT: 70*)
 (*$ BIT: 71*)
 (*$ BIT: 72*)
 (*$ BIT: 73*)
 (*$ BIT: 74*)
 (*$ BIT: 75*)
 (*$ BIT: 76*)
 (*$ BIT: 77*)
 (*$ BIT: 78*)
 (*$ BIT: 79*)
 (*$ BIT: 80*)
 (*$ BIT: 81*)
 (*$ BIT: 82*)
 (*$ BIT: 83*)
 (*$ BIT: 84*)
 (*$ BIT: 85*)
 (*$ BIT: 86*)
 (*$ BIT: 87*)
 (*$ BIT: 88*)
 (*$ BIT: 89*)
 (*$ BIT: 90*)
 (*$ BIT: 91*)
 (*$ BIT: 92*)
 (*$ BIT: 93*)
 (*$ BIT: 94*)
 (*$ BIT: 95*)
 (*$ BIT: 96*)
 (*$ BIT: 97*)
 (*$ BIT: 98*)
 (*$ BIT: 99*)
 (*$ BIT: 100*)
 (*$ BIT: 101*)
 (*$ BIT: 102*)
 (*$ BIT: 103*)
 (*$ BIT: 104*)
 (*$ BIT: 105*)
 (*$ BIT: 106*)
 (*$ BIT: 107*)
 (*$ BIT: 108*)
 (*$ BIT: 109*)
 (*$ BIT: 110*)
 (*$ BIT: 111*)
 (*$ BIT: 112*)
 (*$ BIT: 113*)
 (*$ BIT: 114*)
 (*$ BIT: 115*)
 (*$ BIT: 116*)
 (*$ BIT: 117*)
 (*$ BIT: 118*)
 (*$ BIT: 119*)
 (*$ BIT: 120*)
 (*$ BIT: 121*)
 (*$ BIT: 122*)
 (*$ BIT: 123*)
 (*$ BIT: 124*)
 (*$ BIT: 125*)
 (*$ BIT: 126*)
 (*$ BIT: 127*)
 (*$ BIT: 128*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 132>"317-448 (TDL lines 544-675) (*$ BIT: 129*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"449 (TDL line 676) (*$ BIT: 130*)"
"(*$ BIT: 131*)"
"(*$ BIT: 132*)
 (*$ BIT: 133*)
 (*$ BIT: 134*)
 (*$ BIT: 135*)
 (*$ BIT: 136*)
 (*$ BIT: 137*)
 (*$ BIT: 138*)
 (*$ BIT: 139*)
 (*$ BIT: 140*)
 (*$ BIT: 141*)
 (*$ BIT: 142*)
 (*$ BIT: 143*)
 (*$ BIT: 144*)
 (*$ BIT: 145*)
 (*$ BIT: 146*)
 (*$ BIT: 147*)
 (*$ BIT: 148*)
 (*$ BIT: 149*)
 (*$ BIT: 150*)
 (*$ BIT: 151*)
 (*$ BIT: 152*)
 (*$ BIT: 153*)
 (*$ BIT: 154*)
 (*$ BIT: 155*)
 (*$ BIT: 156*)
 (*$ BIT: 157*)
 (*$ BIT: 158*)
 (*$ BIT: 159*)
 (*$ BIT: 160*)
 (*$ BIT: 161*)
 (*$ BIT: 162*)
 (*$ BIT: 163*)
 (*$ BIT: 164*)
 (*$ BIT: 165*)
 (*$ BIT: 166*)
 (*$ BIT: 167*)
 (*$ BIT: 168*)
 (*$ BIT: 169*)
 (*$ BIT: 170*)
 (*$ BIT: 171*)
 (*$ BIT: 172*)
 (*$ BIT: 173*)
 (*$ BIT: 174*)
 (*$ BIT: 175*)
 (*$ BIT: 176*)
 (*$ BIT: 177*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 48>"450-497 (TDL lines 677-724) (*$ BIT: 178*)"
"(*$Shift and Exit DR  BIT: 179 *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"498-499 (TDL lines 725-726) (*$ Update DR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"500 (TDL line 727) (*$ Run Test Idle *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;"501 (TDL line 728) (*$ Run Test Idle *)"

"(*$ Programming flbp enable bit*)

 (*$0101:00000000 *)"
"(*$ Select DR Scan *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"502-503 (TDL lines 733-734) (*$ Select IR Scan *)"
"(*$ Capture IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"504-505 (TDL lines 735-736) (*$ Shift IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"506 (TDL line 737) (*$ BIT: 0*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"507 (TDL line 738) (*$ BIT: 1*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"508 (TDL line 739) (*$ BIT: 2*)"
"(*$ BIT: 3 Shift and Exit IR*)"
"(*$ Update IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"509-511 (TDL lines 740-742) (*$ Select DR Scan *)"
"(*$ Capture DR *)"
"(*$ Shift DR *)
 (*$ BIT: 0*)
 (*$ BIT: 1*)
 (*$ BIT: 2*)
 (*$ BIT: 3*)
 (*$ BIT: 4*)
 (*$ BIT: 5*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 9>"512-520 (TDL lines 743-751) (*$ BIT: 6*)"
"(*$Shift and Exit DR  BIT: 7 *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"521-522 (TDL lines 752-753) (*$ Update DR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"523 (TDL line 754) (*$ Run Test Idle *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;"524 (TDL line 755) (*$ Run Test Idle *)"

"(*$0110:0000000100000000 *)"
"(*$ Select DR Scan *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"525-526 (TDL lines 758-759) (*$ Select IR Scan *)"
"(*$ Capture IR *)"
"(*$ Shift IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"527-529 (TDL lines 760-762) (*$ BIT: 0*)"
"(*$ BIT: 1*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"530-531 (TDL lines 763-764) (*$ BIT: 2*)"
"(*$ BIT: 3 Shift and Exit IR*)"
"(*$ Update IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"532-534 (TDL lines 765-767) (*$ Select DR Scan *)"
"(*$ Capture DR *)"
"(*$ Shift DR *)
 (*$ BIT: 0*)
 (*$ BIT: 1*)
 (*$ BIT: 2*)
 (*$ BIT: 3*)
 (*$ BIT: 4*)
 (*$ BIT: 5*)
 (*$ BIT: 6*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 10>"535-544 (TDL lines 768-777) (*$ BIT: 7*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"545 (TDL line 778) (*$ BIT: 8*)"
"(*$ BIT: 9*)"
"(*$ BIT: 10*)
 (*$ BIT: 11*)
 (*$ BIT: 12*)
 (*$ BIT: 13*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 6>"546-551 (TDL lines 779-784) (*$ BIT: 14*)"
"(*$Shift and Exit DR  BIT: 15 *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"552-553 (TDL lines 785-786) (*$ Update DR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"554 (TDL line 787) (*$ Run Test Idle *)"
"(*$ Run Test Idle *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"555-556 (TDL lines 788-789)"

"(*$ Programming rom alias register with offset*)
 (*$0101:00001000 *)"
"(*$ Select DR Scan *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"557-558 (TDL lines 794-795) (*$ Select IR Scan *)"
"(*$ Capture IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"559-560 (TDL lines 796-797) (*$ Shift IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"561 (TDL line 798) (*$ BIT: 0*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"562 (TDL line 799) (*$ BIT: 1*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"563 (TDL line 800) (*$ BIT: 2*)"
"(*$ Shift and Exit1 IR; BIT: 3*)"
"(*$ Update IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"564-566 (TDL lines 801-803) (*$ Select DR Scan *)"
"(*$ Capture DR *)"
"(*$ Shift DR *)
 (*$ BIT: 0*)
 (*$ BIT: 1*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 5>"567-571 (TDL lines 804-808) (*$ BIT: 2*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"572 (TDL line 809) (*$ BIT: 3*)"
"(*$ BIT: 4*)"
"(*$ BIT: 5*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"573-575 (TDL lines 810-812) (*$ BIT: 6*)"
"(*$ Shift and Exit1 DR; BIT: 7 *)"
"(*$0110:1001111100000000 *)
 (*$ Update DR *)
 (*$ Select DR Scan *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 4>"576-579 (TDL lines 813-817) (*$ Select IR Scan *)"
"(*$ Capture IR *)"
"(*$ Shift IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"580-582 (TDL lines 818-820) (*$ BIT: 0*)"
"(*$ BIT: 1*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"583-584 (TDL lines 821-822) (*$ BIT: 2*)"
"(*$ Shift and Exit1 IR; BIT: 3*)"
"(*$ Update IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"585-587 (TDL lines 823-825) (*$ Select DR Scan *)"
"(*$ Capture DR *)"
"(*$ Shift DR *)
 (*$ BIT: 0*)
 (*$ BIT: 1*)
 (*$ BIT: 2*)
 (*$ BIT: 3*)
 (*$ BIT: 4*)
 (*$ BIT: 5*)
 (*$ BIT: 6*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 10>"588-597 (TDL lines 826-835) (*$ BIT: 7*)"
"(*$ BIT: 8*)"
"(*$ BIT: 9*)
 (*$ BIT: 10*)
 (*$ BIT: 11*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 5>"598-602 (TDL lines 836-840) (*$ BIT: 12*)"
"(*$ BIT: 13*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"603-604 (TDL lines 841-842) (*$ BIT: 14*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHHCMMMMMMMMMMMMMMMMMLMMMMM*;"605 (TDL line 843) (*$ Shift and Exit1 DR; BIT: 15 *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;"606 (TDL line 844) (*$ Update DR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"607 (TDL line 845) (*$ Run Test Idle *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;"608 (TDL line 846) (*$ Run Test Idle *)"

"(*$ Entering DMLED TEST mode testmode_reg = 0x1003 *)
 (*$0100:11000000000000000001000000000011 *)"
"(*$ Select DR Scan *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"609-610 (TDL lines 852-853) (*$ Select IR Scan *)"
"(*$ Capture IR *)"
"(*$ Shift IR *)
 (*$ BIT: 0*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 4>"611-614 (TDL lines 854-857) (*$ BIT: 1*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"615 (TDL line 858) (*$ BIT: 2*)"
"(*$ BIT: 3 Shift and Exit IR*)"
"(*$ Update IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"616-618 (TDL lines 859-861) (*$ Select DR Scan *)"
"(*$ Capture DR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"619-620 (TDL lines 862-863) (*$ Shift DR *)"
"(*$ BIT: 0*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"621-622 (TDL lines 864-865) (*$ BIT: 1*)"
"(*$ BIT: 2*)"
"(*$ BIT: 3*)
 (*$ BIT: 4*)
 (*$ BIT: 5*)
 (*$ BIT: 6*)
 (*$ BIT: 7*)
 (*$ BIT: 8*)
 (*$ BIT: 9*)
 (*$ BIT: 10*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 10>"623-632 (TDL lines 866-875) (*$ BIT: 11*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"633 (TDL line 876) (*$ BIT: 12*)"
"(*$ BIT: 13*)"
"(*$ BIT: 14*)
 (*$ BIT: 15*)
 (*$ BIT: 16*)
 (*$ BIT: 17*)
 (*$ BIT: 18*)
 (*$ BIT: 19*)
 (*$ BIT: 20*)
 (*$ BIT: 21*)
 (*$ BIT: 22*)
 (*$ BIT: 23*)
 (*$ BIT: 24*)
 (*$ BIT: 25*)
 (*$ BIT: 26*)
 (*$ BIT: 27*)
 (*$ BIT: 28*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 17>"634-650 (TDL lines 877-893) (*$ BIT: 29*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"651 (TDL line 894) (*$ BIT: 30*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHHCMMMMMMMMMMMMMMMMMLMMMMM*;"652 (TDL line 895) (*$Shift and Exit DR  BIT: 31 *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;"653 (TDL line 896) (*$ Update DR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"654 (TDL line 897) (*$ Run Test Idle *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;"655 (TDL line 898) (*$ Run Test Idle *)"

"(*$0101:00010000 *)"
"(*$ Select DR Scan *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"656-657 (TDL lines 901-902) (*$ Select IR Scan *)"
"(*$ Capture IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"658-659 (TDL lines 903-904) (*$ Shift IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"660 (TDL line 905) (*$ BIT: 0*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"661 (TDL line 906) (*$ BIT: 1*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"662 (TDL line 907) (*$ BIT: 2*)"
"(*$ BIT: 3 Shift and Exit IR*)"
"(*$ Update IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"663-665 (TDL lines 908-910) (*$ Select DR Scan *)"
"(*$ Capture DR *)"
"(*$ Shift DR *)
 (*$ BIT: 0*)
 (*$ BIT: 1*)
 (*$ BIT: 2*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 6>"666-671 (TDL lines 911-916) (*$ BIT: 3*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"672 (TDL line 917) (*$ BIT: 4*)"
"(*$ BIT: 5*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"673-674 (TDL lines 918-919) (*$ BIT: 6*)"
"(*$Shift and Exit DR  BIT: 7 *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"675-676 (TDL lines 920-921) (*$ Update DR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"677 (TDL line 922) (*$ Run Test Idle *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;"678 (TDL line 923) (*$ Run Test Idle *)"

"(*$0110:0000000000000000 *)
 (*$ Reset DMLED IP *)"
"(*$ Select DR Scan *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"679-680 (TDL lines 927-928) (*$ Select IR Scan *)"
"(*$ Capture IR *)"
"(*$ Shift IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"681-683 (TDL lines 929-931) (*$ BIT: 0*)"
"(*$ BIT: 1*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"684-685 (TDL lines 932-933) (*$ BIT: 2*)"
"(*$ BIT: 3 Shift and Exit IR*)"
"(*$ Update IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"686-688 (TDL lines 934-936) (*$ Select DR Scan *)"
"(*$ Capture DR *)"
"(*$ Shift DR *)
 (*$ BIT: 0 DMLED resetn*)
 (*$ BIT: 1 DMLED system enable*)
 (*$ BIT: 2 DMLED enable*)
 (*$ BIT: 3 DMLED loadnDump*)
 (*$ BIT: 4*)
 (*$ BIT: 5*)
 (*$ BIT: 6*)
 (*$ BIT: 7*)
 (*$ BIT: 8*)
 (*$ BIT: 9*)
 (*$ BIT: 10*)
 (*$ BIT: 11*)
 (*$ BIT: 12*)
 (*$ BIT: 13*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 17>"689-705 (TDL lines 937-953) (*$ BIT: 14*)"
"(*$Shift and Exit DR  BIT: 15 *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"706-707 (TDL lines 954-955) (*$ Update DR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"708 (TDL line 956) (*$ Run Test Idle *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;"709 (TDL line 957) (*$ Run Test Idle *)"

"(*$0110:0000000000000001 *)"
"(*$ Select DR Scan *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"710-711 (TDL lines 961-962) (*$ Select IR Scan *)"
"(*$ Capture IR *)"
"(*$ Shift IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"712-714 (TDL lines 963-965) (*$ BIT: 0*)"
"(*$ BIT: 1*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"715-716 (TDL lines 966-967) (*$ BIT: 2*)"
"(*$ BIT: 3 Shift and Exit IR*)"
"(*$ Update IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"717-719 (TDL lines 968-970) (*$ Select DR Scan *)"
"(*$ Capture DR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"720-721 (TDL lines 971-972) (*$ Shift DR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"722 (TDL line 973) (*$ BIT: 0 Lifting the DMLED reset*)"
"(*$ BIT: 1 DMLED system enable*)"
"(*$ BIT: 2 DMLED enable*)
 (*$ BIT: 3 DMLED loadnDump*)
 (*$ BIT: 4*)
 (*$ BIT: 5*)
 (*$ BIT: 6*)
 (*$ BIT: 7*)
 (*$ BIT: 8*)
 (*$ BIT: 9*)
 (*$ BIT: 10*)
 (*$ BIT: 11*)
 (*$ BIT: 12*)
 (*$ BIT: 13*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 14>"723-736 (TDL lines 974-987) (*$ BIT: 14*)"
"(*$Shift and Exit DR  BIT: 15 *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"737-738 (TDL lines 988-989) (*$ Update DR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"739 (TDL line 990) (*$ Run Test Idle *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;"740 (TDL line 991) (*$ Run Test Idle *)"

"(*$0110:0000000000000111 *)"
"(*$ Select DR Scan *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"741-742 (TDL lines 994-995) (*$ Select IR Scan *)"
"(*$ Capture IR *)"
"(*$ Shift IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"743-745 (TDL lines 996-998) (*$ BIT: 0*)"
"(*$ BIT: 1*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"746-747 (TDL lines 999-1000) (*$ BIT: 2*)"
"(*$ BIT: 3 Shift and Exit IR*)"
"(*$ Update IR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"748-750 (TDL lines 1001-1003) (*$ Select DR Scan *)"
"(*$ Capture DR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"751-752 (TDL lines 1004-1005) (*$ Shift DR *)"
"(*$ BIT: 0 DMLED reset*)"
"(*$ BIT: 1 DMLED system enable*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"753-755 (TDL lines 1006-1008) (*$ BIT: 2 DMLED enable*)"
"(*$ BIT: 3 DMLED loadndump*)"
"(*$ BIT: 4*)
 (*$ BIT: 5*)
 (*$ BIT: 6*)
 (*$ BIT: 7*)
 (*$ BIT: 8*)
 (*$ BIT: 9*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 8>"756-763 (TDL lines 1009-1016) (*$ BIT: 10*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMHLCMMMMMMMMMMMMMMMMMLMMMMM*;"764 (TDL line 1017) (*$ BIT: 11*)"
"(*$ BIT: 12*)"
"(*$ BIT: 13*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 3>"765-767 (TDL lines 1018-1020) (*$ BIT: 14*)"
"(*$Shift and Exit DR  BIT: 15 *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLHCMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 2>"768-769 (TDL lines 1021-1022) (*$ Update DR *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLCMMMMMMMMMMMMMMMMMLMMMMM*;"770 (TDL line 1023) (*$ Run Test Idle *)"
"(*$ Run Test Idle *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;<RPT 12>"771-782 (TDL lines 1024-1026)"
"(*$ Sending out SIZE word. No of words to be read *)
 (*$ 0x0001_0000_0000_0000 = 4096 32 bit words will be read *)
 (*$ Prepare DMLED IP for reads *)
 (*$ Sending out addr word 0x0000_0000_0000_0000 RAM1/2 have 12 bit address bus*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMCMMMMM*;<RPT 32>"783-814 (TDL lines 1027-1060)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMHLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMCMMMMM*;"815 (TDL line 1061)"
"(*$ Sending out control word *)
 (*$ ctrl_word[3:0] = wait_states *)
 (*$ ctrl_word[4] = 0: RAM1 is enabled, 1: RAM2 is enabled *)
 (*$ ctrl_word[5] = Reserved *)
 (*$ ctrl_word[8:6] = tester bus width: 010 = 4 bits *)
 (*$ ctrl_word[15:9] = Reserved *)
 (*$ 0 wait_state_0*)
 (*$ 0 wait_state_1*)
 (*$ 0 wait_state_2*)
 (*$ 0 wait_state_3*)
 (*$ 0 0: RAM1 enabled, 1: RAM2 enabled*)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMCMMMMM*;<RPT 10>"816-825 (TDL lines 1062-1077)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMHLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMCMMMMM*;"826 (TDL line 1078)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMCMMMMM*;<RPT 16>"827-842 (TDL lines 1079-1087)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;"843 (TDL line 1088)"

"(*$ begin INCLUDE: TDLS/dmled_read.inc *)"
"TEST_PROC (INCLUDE_INFO)  (TDL line 2)"
"      INCLUDE_DATE = 'Nov/4/2011';"
"  INCLUDE_REVISION = '2.2';"
"  INCLUDE_SET_NAME = 'dmled_read.inc';"

"(*$ 0x00000000 *)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMLLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMCMMMMM*;<RPT 16>"844-859 (TDL lines 9-24)"

"(*$ end INCLUDE: TDLS/dmled_read.inc *)"

" end regular TDL patterns; start wrapup "

*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM---MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMM*;<RPT 4>
$dmled_read_DPM_end
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM---MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMM*;
}
