Unison:U0.1:S4.3;

Pattern jtag_reset_init {

Mode Digital;
Type Generic;

Default SignalHeader DefaultSignalHeader;

Default WaveformTable WFT5;

" Processed by Jazz::Tvt::tvtFusion version 1.205.0, updated Feb 21, 2012 "
" TDL:  jtag_reset_init.tdl "
" Generated:  Mon Mar  5 14:50:58 US/Central 2012 "
" Jazz dir: /data/mkoe/ttarsi/Blizzard "

" ASIC_VERSION = 4.0 "
" "
" ASIC_TITLE = 'LIBRARY_TYPE = GS60, "
"                   CUSTOMER = TEXASINSTRUMENTS, "
"             TI_PART_NUMBER = F771727, "
"           PATTERN_SET_NAME = jtag_reset_init, "
"           PATTERN_SET_TYPE = FUNC,NOSTROBE, "
"    PATTERN_SET_DESCRIPTION = , "
"                   REVISION = 2.0, "
"                       DATE = 8/8/2011'; "

/*   PATTERN 0 Vector 0 TesterCycle 0   */
/*
"AAAAPPrPPPAAAAAAAAPPPPPPPPPCCCCooPPPPPPPPPPRPPPPPFFFPPPPPPPPPTTTTPPPPPwhXXPPPPPPLLLLLLROOUUPPPiLLLLLLPPPPTTTTPPPPPRPPCCPPAAAAAAAAAAAA"
"IIIIQQbBBQIIITIIIINHHHHHHHH0011__AAAAAAGGPPAQQQQQLLLGGGGGGFFFRRRRFNNNNaiOOPPPPMMPPPPPPSSSSSBBBaPPPPPPKKKKDDMCNJJJJAPO22JJIIIIIIIIIIII"
"NNNN01i672NNNENNNN276543210____cc2345677625W34567AAA543210765DDDD37654kbSS341076CCCCCCTCCBB012_CCCCCC7654OISK30123W6R__67NNNNNNNNNNNN"
"1111__a___000S1111_________nppnpp__________P_____SSS_________3210_____e_CC______000000_0100___f000000_____________P__pn__222211000000"
"543256s111012T6789222333344____uu4455555555O66666HHH777788888____99999_n01111111CSACSPn__DD111tRFAAAA1111111111111O1O__11321010987654"
"____  _056___ ____7890567014444__8901456789R12345345678901456888914567n___000011LE2LCD_11MP233eERDDDD4444455555566R6R1177____________"
"1234  9   111 2222         2345df          _     ___         7890     _911678901KR0KI_122__901sSA01231234901238901_3I7767111111111111"
"          789 3456             oa          n     777                  9900      _I_R_n24511   tEM____             N D45  778888889999"
"                               ni          _     012                  8 02      1R1Un_2  22   aTE1111             _ E    890123890123"
"                               el          6                                    1Q1N_1   78   d__3334             T _                "
"                               __          0                                    6_8_12        cnn7890             E 1                "
"                               44                                                1 n21        ___                 S 6                "
"                               67                                                1 _0         111                 T 4                "
"                                                                                 7 1          333                 _                  "
"                                                                                   1          256                 1                  "
"                                                                                   9                              6                  "
"                                                                                                                  2                  "
*/
$jtag_reset_init_st
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMHLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMMM*;"1 (TDL line 171)"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMHLMMMMMMLMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMMM*;<RPT 5300>"2-5301 (TDL line 174)"

" end regular TDL patterns; start wrapup "

*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;"extra to meet minimum of 32"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;<RPT 4>
$jtag_reset_init_end
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMM-MMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMMM*;
}
