Unison:U0.2:S4.3;

Pattern pb_vl_dtxn2_2p_v23_CPM {

Mode Digital;
Type Generic;



Default SignalHeader DefaultSignalHeader;

Default WaveformTable WFT20;

" Processed by Jazz::Tvt::tvtFusion version 1.199.0, updated Nov 22, 2011 "
" TDL:  TDLS/pb_vl_dtxn2_2p_v23.tdl.gz "
" Generated:  Wed Dec 28 17:58:22 US/Central 2011 "
" Jazz dir: /data/jazztest4/vikas/Phoenix_Unison/Blizzard_FX1 "

" ASIC_VERSION = 7.0 "
" "
" ASIC_TITLE = 'LIBRARY_TYPE = GS60, "
"                   CUSTOMER = TexasInstruments, "
"             TI_PART_NUMBER = F771727B, "
"           PATTERN_SET_NAME = pb_vl_dtxn2_2p_v23, "
"           PATTERN_SET_TYPE = BIST_MEMORY_AC,VBOXLO_MEMORY, "
"    PATTERN_SET_DESCRIPTION = , "
"                   REVISION = 2.3, "
"                       DATE = 09/01/11'; "

/*                                                        */
/*   TDL91 7.0 FORMAT TEST PATTERNS PRODUCED BY pbistTdlGen v 3.1.1 /tdlProcedures.pm    */
/*   FILENAME : pb_vl_dtxn2_2p.tdl   */
/**/
/*     Started Reset Mode Entry Sequence        */
/*   Assert reset   */
/*
"AAAAPPrPPPAAAAPPPPPPPPPCCCCooPPPPPPPPPPRPPPPPFFFPPPPPPPPPTTTTPPPPPwhXXPPPPPPLLLLLLROOUUPPPiLLLLLLPPPPTTTTPPPPPRPPCCPPAAAAAAAAAAA"
"IIIIQQbBBQIIIINHHHHHHHH0011__AAAAAAGGPPAQQQQQLLLGGGGGGFFFRRRRFNNNNaiOOPPPPMMPPPPPPSSSSSBBBaPPPPPPKKKKDDMCNJJJJAPO22JJIIIIIIIIIII"
"NNNN01i672NNNN276543210____cc2345677625W34567AAA543210765DDDD37654kbSS341076CCCCCCTCCBB012_CCCCCC7654OISK30123W6R__67NNNNNNNNNNN"
"1111__a___1111_________nppnpp__________P_____SSS_________3210_____e_CC______000000_0100___f000000_____________P__pn__22221100000"
"543256s1116789222333344____uu4455555555O66666HHH777788888____99999_n01111111CSACSPn__DD111tRFAAAA1111111111111O1O__1132101098765"
"____  _056____7890567014444__8901456789R12345345678901456888914567n___000011LE2LCD_11MP233eERDDDD4444455555566R6R1177___________"
"1234  9   2222         2345df          _     ___         7890     _911678901KR0KI_122__901sSA01231234901238901_3I776711111111111"
"          3456             oa          n     777                  9900      _I_R_n24511   tEM____             N D45  77888888999"
"                           ni          _     012                  8 02      1R1Un_2  22   aTE1111             _ E    89012389012"
"                           el          6                                    1Q1N_1   78   d__3334             T _               "
"                           __          0                                    6_8_12        cnn7890             E 1               "
"                           44                                                1 n21        ___                 S 6               "
"                           67                                                1 _0         111                 T 4               "
"                                                                             7 1          333                 _                 "
"                                                                               1          256                 1                 "
"                                                                               9                              6                 "
"                                                                                                              2                 "
*/
$pb_vl_dtxn2_2p_v23_CPM_st
*-----------------------------------------------------------------------------------<--------------------------------------------*;<SWCCPM>
*-----------------------------------------------------------------------------------<--------------------------------------------*;<LDA pb_vl_dtxn2_2p_v23_DPM_st,COND NZC2>
*-----------------------------------------------------------------------------------<--------------------------------------------*;<RPT 128>

" end initialization; start regular patterns "

*dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd*;<SWCDPM,SDP,RPT 18326> "1-18326"

"LOOP_FOR_MATCH FAIL, 558"
"loop setup"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <SWCCPM,LC2 4> "Load counter and test pins prior entering match loop"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL ON,TCI ON)> "ignore fail and inhibit count during loop for match"
"outer loop control"
$pb_vl_dtxn2_2p_v23_loop1
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND NZC2>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_match1,DC2>
"loop for match unmatch"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF)> "LOOP_FOR_MATCH failed at least on one site, enable fails"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 10> "test LOOP_FOR_MATCH pin on all sites with fails active"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <JMP pb_vl_dtxn2_2p_v23_continue1> "passing sites continue execution"
"match block"
$pb_vl_dtxn2_2p_v23_match1
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <FLAG(SEQF OFF)> "clear sequential fail flag"
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND SEQF> "if vector fails then SEQF is set to on and match loop continues"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 150>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_loop1>
$pb_vl_dtxn2_2p_v23_continue1
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF,TCI OFF)> "matched so now switch back to normal mode"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;
"end of match loop"

*dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd*;<SWCDPM,SDP,RPT 1381> "18885-20265"

"LOOP_FOR_MATCH FAIL, 558"
"loop setup"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <SWCCPM,LC2 4> "Load counter and test pins prior entering match loop"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL ON,TCI ON)> "ignore fail and inhibit count during loop for match"
"outer loop control"
$pb_vl_dtxn2_2p_v23_loop2
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND NZC2>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_match2,DC2>
"loop for match unmatch"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF)> "LOOP_FOR_MATCH failed at least on one site, enable fails"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 10> "test LOOP_FOR_MATCH pin on all sites with fails active"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <JMP pb_vl_dtxn2_2p_v23_continue2> "passing sites continue execution"
"match block"
$pb_vl_dtxn2_2p_v23_match2
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <FLAG(SEQF OFF)> "clear sequential fail flag"
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND SEQF> "if vector fails then SEQF is set to on and match loop continues"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 150>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_loop2>
$pb_vl_dtxn2_2p_v23_continue2
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF,TCI OFF)> "matched so now switch back to normal mode"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;
"end of match loop"

*dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd*;<SWCDPM,SDP,RPT 1381> "20824-22204"

"LOOP_FOR_MATCH FAIL, 558"
"loop setup"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <SWCCPM,LC2 4> "Load counter and test pins prior entering match loop"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL ON,TCI ON)> "ignore fail and inhibit count during loop for match"
"outer loop control"
$pb_vl_dtxn2_2p_v23_loop3
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND NZC2>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_match3,DC2>
"loop for match unmatch"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF)> "LOOP_FOR_MATCH failed at least on one site, enable fails"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 10> "test LOOP_FOR_MATCH pin on all sites with fails active"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <JMP pb_vl_dtxn2_2p_v23_continue3> "passing sites continue execution"
"match block"
$pb_vl_dtxn2_2p_v23_match3
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <FLAG(SEQF OFF)> "clear sequential fail flag"
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND SEQF> "if vector fails then SEQF is set to on and match loop continues"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 150>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_loop3>
$pb_vl_dtxn2_2p_v23_continue3
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF,TCI OFF)> "matched so now switch back to normal mode"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;
"end of match loop"

*dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd*;<SWCDPM,SDP,RPT 1381> "22763-24143"

"LOOP_FOR_MATCH FAIL, 558"
"loop setup"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <SWCCPM,LC2 4> "Load counter and test pins prior entering match loop"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL ON,TCI ON)> "ignore fail and inhibit count during loop for match"
"outer loop control"
$pb_vl_dtxn2_2p_v23_loop4
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND NZC2>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_match4,DC2>
"loop for match unmatch"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF)> "LOOP_FOR_MATCH failed at least on one site, enable fails"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 10> "test LOOP_FOR_MATCH pin on all sites with fails active"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <JMP pb_vl_dtxn2_2p_v23_continue4> "passing sites continue execution"
"match block"
$pb_vl_dtxn2_2p_v23_match4
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <FLAG(SEQF OFF)> "clear sequential fail flag"
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND SEQF> "if vector fails then SEQF is set to on and match loop continues"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 150>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_loop4>
$pb_vl_dtxn2_2p_v23_continue4
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF,TCI OFF)> "matched so now switch back to normal mode"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;
"end of match loop"

*dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd*;<SWCDPM,SDP,RPT 1381> "24702-26082"

"LOOP_FOR_MATCH FAIL, 558"
"loop setup"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <SWCCPM,LC2 4> "Load counter and test pins prior entering match loop"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL ON,TCI ON)> "ignore fail and inhibit count during loop for match"
"outer loop control"
$pb_vl_dtxn2_2p_v23_loop5
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND NZC2>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_match5,DC2>
"loop for match unmatch"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF)> "LOOP_FOR_MATCH failed at least on one site, enable fails"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 10> "test LOOP_FOR_MATCH pin on all sites with fails active"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <JMP pb_vl_dtxn2_2p_v23_continue5> "passing sites continue execution"
"match block"
$pb_vl_dtxn2_2p_v23_match5
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <FLAG(SEQF OFF)> "clear sequential fail flag"
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND SEQF> "if vector fails then SEQF is set to on and match loop continues"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 150>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_loop5>
$pb_vl_dtxn2_2p_v23_continue5
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF,TCI OFF)> "matched so now switch back to normal mode"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;
"end of match loop"

*dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd*;<SWCDPM,SDP,RPT 1381> "26641-28021"

"LOOP_FOR_MATCH FAIL, 558"
"loop setup"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <SWCCPM,LC2 4> "Load counter and test pins prior entering match loop"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL ON,TCI ON)> "ignore fail and inhibit count during loop for match"
"outer loop control"
$pb_vl_dtxn2_2p_v23_loop6
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND NZC2>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_match6,DC2>
"loop for match unmatch"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF)> "LOOP_FOR_MATCH failed at least on one site, enable fails"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 10> "test LOOP_FOR_MATCH pin on all sites with fails active"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <JMP pb_vl_dtxn2_2p_v23_continue6> "passing sites continue execution"
"match block"
$pb_vl_dtxn2_2p_v23_match6
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <FLAG(SEQF OFF)> "clear sequential fail flag"
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND SEQF> "if vector fails then SEQF is set to on and match loop continues"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 150>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_loop6>
$pb_vl_dtxn2_2p_v23_continue6
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF,TCI OFF)> "matched so now switch back to normal mode"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;
"end of match loop"

*dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd*;<SWCDPM,SDP,RPT 1381> "28580-29960"

"LOOP_FOR_MATCH FAIL, 558"
"loop setup"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <SWCCPM,LC2 4> "Load counter and test pins prior entering match loop"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL ON,TCI ON)> "ignore fail and inhibit count during loop for match"
"outer loop control"
$pb_vl_dtxn2_2p_v23_loop7
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND NZC2>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_match7,DC2>
"loop for match unmatch"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF)> "LOOP_FOR_MATCH failed at least on one site, enable fails"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 10> "test LOOP_FOR_MATCH pin on all sites with fails active"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <JMP pb_vl_dtxn2_2p_v23_continue7> "passing sites continue execution"
"match block"
$pb_vl_dtxn2_2p_v23_match7
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <FLAG(SEQF OFF)> "clear sequential fail flag"
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND SEQF> "if vector fails then SEQF is set to on and match loop continues"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 150>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_loop7>
$pb_vl_dtxn2_2p_v23_continue7
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF,TCI OFF)> "matched so now switch back to normal mode"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;
"end of match loop"

*dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd*;<SWCDPM,SDP,RPT 1381> "30519-31899"

"LOOP_FOR_MATCH FAIL, 558"
"loop setup"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <SWCCPM,LC2 4> "Load counter and test pins prior entering match loop"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL ON,TCI ON)> "ignore fail and inhibit count during loop for match"
"outer loop control"
$pb_vl_dtxn2_2p_v23_loop8
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND NZC2>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_match8,DC2>
"loop for match unmatch"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF)> "LOOP_FOR_MATCH failed at least on one site, enable fails"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 10> "test LOOP_FOR_MATCH pin on all sites with fails active"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <JMP pb_vl_dtxn2_2p_v23_continue8> "passing sites continue execution"
"match block"
$pb_vl_dtxn2_2p_v23_match8
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <FLAG(SEQF OFF)> "clear sequential fail flag"
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND SEQF> "if vector fails then SEQF is set to on and match loop continues"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 150>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_loop8>
$pb_vl_dtxn2_2p_v23_continue8
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF,TCI OFF)> "matched so now switch back to normal mode"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;
"end of match loop"

*dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd*;<SWCDPM,SDP,RPT 1381> "32458-33838"

"LOOP_FOR_MATCH FAIL, 558"
"loop setup"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <SWCCPM,LC2 4> "Load counter and test pins prior entering match loop"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL ON,TCI ON)> "ignore fail and inhibit count during loop for match"
"outer loop control"
$pb_vl_dtxn2_2p_v23_loop9
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND NZC2>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_match9,DC2>
"loop for match unmatch"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF)> "LOOP_FOR_MATCH failed at least on one site, enable fails"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 10> "test LOOP_FOR_MATCH pin on all sites with fails active"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <JMP pb_vl_dtxn2_2p_v23_continue9> "passing sites continue execution"
"match block"
$pb_vl_dtxn2_2p_v23_match9
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <FLAG(SEQF OFF)> "clear sequential fail flag"
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND SEQF> "if vector fails then SEQF is set to on and match loop continues"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 150>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_loop9>
$pb_vl_dtxn2_2p_v23_continue9
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF,TCI OFF)> "matched so now switch back to normal mode"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;
"end of match loop"

*dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd*;<SWCDPM,SDP,RPT 1381> "34397-35777"

"LOOP_FOR_MATCH FAIL, 558"
"loop setup"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <SWCCPM,LC2 4> "Load counter and test pins prior entering match loop"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL ON,TCI ON)> "ignore fail and inhibit count during loop for match"
"outer loop control"
$pb_vl_dtxn2_2p_v23_loop10
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND NZC2>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_match10,DC2>
"loop for match unmatch"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF)> "LOOP_FOR_MATCH failed at least on one site, enable fails"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 10> "test LOOP_FOR_MATCH pin on all sites with fails active"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <JMP pb_vl_dtxn2_2p_v23_continue10> "passing sites continue execution"
"match block"
$pb_vl_dtxn2_2p_v23_match10
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <FLAG(SEQF OFF)> "clear sequential fail flag"
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND SEQF> "if vector fails then SEQF is set to on and match loop continues"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 150>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_loop10>
$pb_vl_dtxn2_2p_v23_continue10
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF,TCI OFF)> "matched so now switch back to normal mode"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;
"end of match loop"

*dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd*;<SWCDPM,SDP,RPT 1381> "36336-37716"

"LOOP_FOR_MATCH FAIL, 558"
"loop setup"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <SWCCPM,LC2 4> "Load counter and test pins prior entering match loop"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL ON,TCI ON)> "ignore fail and inhibit count during loop for match"
"outer loop control"
$pb_vl_dtxn2_2p_v23_loop11
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND NZC2>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_match11,DC2>
"loop for match unmatch"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF)> "LOOP_FOR_MATCH failed at least on one site, enable fails"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 10> "test LOOP_FOR_MATCH pin on all sites with fails active"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <JMP pb_vl_dtxn2_2p_v23_continue11> "passing sites continue execution"
"match block"
$pb_vl_dtxn2_2p_v23_match11
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <FLAG(SEQF OFF)> "clear sequential fail flag"
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND SEQF> "if vector fails then SEQF is set to on and match loop continues"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 150>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_loop11>
$pb_vl_dtxn2_2p_v23_continue11
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF,TCI OFF)> "matched so now switch back to normal mode"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;
"end of match loop"

*dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd*;<SWCDPM,SDP,RPT 1381> "38275-39655"

"LOOP_FOR_MATCH FAIL, 558"
"loop setup"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <SWCCPM,LC2 4> "Load counter and test pins prior entering match loop"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL ON,TCI ON)> "ignore fail and inhibit count during loop for match"
"outer loop control"
$pb_vl_dtxn2_2p_v23_loop12
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND NZC2>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_match12,DC2>
"loop for match unmatch"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF)> "LOOP_FOR_MATCH failed at least on one site, enable fails"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 10> "test LOOP_FOR_MATCH pin on all sites with fails active"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <JMP pb_vl_dtxn2_2p_v23_continue12> "passing sites continue execution"
"match block"
$pb_vl_dtxn2_2p_v23_match12
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <FLAG(SEQF OFF)> "clear sequential fail flag"
*MMMMMMMMMMMMMMMMMMMMMMMMMMM10HHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <COND SEQF> "if vector fails then SEQF is set to on and match loop continues"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <RPT 150>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <CJMP pb_vl_dtxn2_2p_v23_loop12>
$pb_vl_dtxn2_2p_v23_continue12
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*; <MODE(IFAIL OFF,TCI OFF)> "matched so now switch back to normal mode"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMHHHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMLMMMMMMMMMMMMMH<MMMMMMMMMMMMMMMMMMLLLMMMMMMMMMMMMMMMMMLMMMMM*;
"end of match loop"


" end regular patterns; start wrapup "

*dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd*;<SWCDPM,SDP,RPT 58> "33518-33575"
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMM----MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMMMMMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMM*;<SWCCPM>
$pb_vl_dtxn2_2p_v23_CPM_end
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMM----MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMMMMMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMM*;<RET>
*MMMMMMMMMMMMMMMMMMMMMMMMMMMMM----MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-MMMMMMMMMMMMM--MMMMMMMMMMMMMMMMMM---MMMMMMMMMMMMMMMMM-MMMMM*;<RPT 512>
}
